# Generated by Django 4.1.7 on 2023-03-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_ordermodel_city_ordermodel_email_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
