# Generated by Django 4.1.7 on 2023-03-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_ordermodel_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
